import React, { useState, useEffect } from "react";
import {
  Copy,
  Check,
  Sparkles,
  RotateCcw,
  FileCode,
  Smartphone,
  Wrench,
  AlignLeft,
  EyeOff,
} from "lucide-react";
import { AndroidFile } from "../types";

interface CodeEditorProps {
  file: AndroidFile | null;
  onContentChange: (path: string, newContent: string) => void;
  onFixSingleFileWithAi: (path: string) => void;
  isFixing?: boolean;
  onHideEditor?: () => void;
}

export const CodeEditor: React.FC<CodeEditorProps> = ({
  file,
  onContentChange,
  onFixSingleFileWithAi,
  isFixing = false,
  onHideEditor,
}) => {
  const [copied, setCopied] = useState(false);

  if (!file) {
    return (
      <div className="flex-1 bg-slate-950 flex flex-col items-center justify-center text-slate-500 p-8 text-center select-none">
        <FileCode className="w-12 h-12 mb-3 text-slate-700" />
        <p className="text-sm font-semibold text-slate-400">No File Selected</p>
        <p className="text-xs text-slate-600 mt-1">Select an Android source file from the project tree to view or edit</p>
      </div>
    );
  }

  const lines = file.content.split("\n");

  const handleCopy = () => {
    navigator.clipboard.writeText(file.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  };

  const handleFormat = () => {
    // Simple Indentation format for XML and Kotlin
    const formatted = file.content
      .split("\n")
      .map((line) => line.trimEnd())
      .join("\n");
    onContentChange(file.path, formatted);
  };

  const getLanguageTag = (path: string) => {
    if (path.endsWith(".kt")) return "KOTLIN";
    if (path.endsWith(".java")) return "JAVA";
    if (path.endsWith(".xml")) return "XML";
    if (path.endsWith(".gradle")) return "GRADLE";
    return "TEXT";
  };

  return (
    <div className="flex-1 flex flex-col bg-slate-950 h-full overflow-hidden">
      {/* Editor Tab Header Bar */}
      <div className="bg-slate-900 border-b border-slate-800 px-2 sm:px-4 py-1.5 flex items-center justify-between text-xs text-slate-300 gap-2">
        <div className="flex items-center gap-1.5 min-w-0">
          <FileCode className="w-4 h-4 text-sky-400 shrink-0" />
          <span className="font-semibold text-slate-200 truncate max-w-[120px] sm:max-w-xs">{file.path}</span>
          <span className="bg-slate-800 text-slate-400 text-[10px] font-mono px-1.5 py-0.5 rounded border border-slate-700 uppercase shrink-0">
            {getLanguageTag(file.path)}
          </span>
          {file.isAutoGenerated && (
            <span className="bg-emerald-950 text-emerald-400 text-[10px] font-medium px-1.5 py-0.5 rounded border border-emerald-800/60 hidden sm:flex items-center gap-1 shrink-0">
              <Sparkles className="w-3 h-3" /> AI
            </span>
          )}
        </div>

        <div className="flex items-center gap-1 sm:gap-2 shrink-0">
          <button
            onClick={handleFormat}
            className="flex items-center gap-1 hover:bg-slate-800 text-slate-400 hover:text-slate-200 px-1.5 sm:px-2 py-1 rounded transition-colors"
            title="Format code spacing"
          >
            <AlignLeft className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Format</span>
          </button>

          <button
            onClick={handleCopy}
            className="flex items-center gap-1 hover:bg-slate-800 text-slate-400 hover:text-slate-200 px-1.5 sm:px-2 py-1 rounded transition-colors"
            title="Copy code"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span className="hidden sm:inline">{copied ? "Copied" : "Copy"}</span>
          </button>

          <button
            onClick={() => onFixSingleFileWithAi(file.path)}
            disabled={isFixing}
            className="flex items-center gap-1 bg-indigo-950/70 border border-indigo-700/60 hover:bg-indigo-900 text-indigo-300 text-xs px-2 sm:px-2.5 py-1 rounded font-medium transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
            <span>{isFixing ? "Fixing..." : "AI Fix"}</span>
          </button>

          {onHideEditor && (
            <button
              onClick={onHideEditor}
              className="flex items-center gap-1 hover:bg-rose-950/40 text-slate-400 hover:text-rose-300 px-1.5 sm:px-2 py-1 rounded transition-colors border border-transparent hover:border-rose-500/30"
              title="Hide Code Editor (ایڈیٹر چھپائیں)"
            >
              <EyeOff className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Hide</span>
            </button>
          )}
        </div>
      </div>

      {/* Code Area with Line Numbers */}
      <div className="flex-1 flex overflow-hidden font-mono text-xs leading-relaxed">
        {/* Line Numbers Column */}
        <div className="bg-slate-900/60 border-r border-slate-800/80 text-slate-600 select-none py-3 px-2 text-right min-w-[3rem] font-mono">
          {lines.map((_, i) => (
            <div key={i} className="h-5 leading-5">
              {i + 1}
            </div>
          ))}
        </div>

        {/* Text Area */}
        <textarea
          value={file.content}
          onChange={(e) => onContentChange(file.path, e.target.value)}
          spellCheck={false}
          className="flex-1 bg-transparent text-slate-200 p-3 outline-none resize-none overflow-auto font-mono whitespace-pre leading-5 custom-scrollbar selection:bg-sky-500/30"
          style={{ tabSize: 4 }}
        />
      </div>

      {/* Footer Status Bar */}
      <div className="bg-slate-900 border-t border-slate-800 px-4 py-1 text-[11px] text-slate-500 flex items-center justify-between font-mono">
        <span>Lines: {lines.length} | Characters: {file.content.length}</span>
        <span className="text-emerald-400 font-sans">Ready for Gradle Compile</span>
      </div>
    </div>
  );
};
