import React, { useState } from "react";
import {
  Folder,
  FolderOpen,
  FileCode,
  FileText,
  Plus,
  Trash2,
  ChevronRight,
  ChevronDown,
  Sparkles,
  AlertCircle,
  Smartphone,
  Search,
  X,
} from "lucide-react";
import { AndroidFile } from "../types";

interface FileTreeProps {
  files: AndroidFile[];
  selectedPath: string;
  onSelectFile: (path: string) => void;
  onAddFile: (path: string) => void;
  onDeleteFile: (path: string) => void;
  ideTheme?: "dark" | "light";
  onCloseMobileFiles?: () => void;
}

export const FileTree: React.FC<FileTreeProps> = ({
  files,
  selectedPath,
  onSelectFile,
  onAddFile,
  onDeleteFile,
  ideTheme = "dark",
  onCloseMobileFiles,
}) => {
  const [searchTerm, setSearchTerm] = useState("");
  const [newFilePath, setNewFilePath] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({
    app: true,
    "app/src": true,
    "app/src/main": true,
    "app/src/main/java": true,
    "app/src/main/res": true,
    "app/src/main/res/layout": true,
    "app/src/main/res/values": true,
  });

  const toggleFolder = (folderPath: string) => {
    setExpandedFolders((prev) => ({ ...prev, [folderPath]: !prev[folderPath] }));
  };

  const handleCreateFile = (e: React.FormEvent) => {
    e.preventDefault();
    if (newFilePath.trim()) {
      let finalPath = newFilePath.trim();
      if (!finalPath.startsWith("app/")) {
        finalPath = `app/src/main/java/com/example/app/${finalPath}`;
      }
      onAddFile(finalPath);
      setNewFilePath("");
      setIsCreating(false);
    }
  };

  // Group files into standard Android Studio view:
  // Manifests, Java/Kotlin, Res, Gradle Scripts
  const filteredFiles = files.filter((f) =>
    f.path.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const manifests = filteredFiles.filter((f) => f.path.toLowerCase().includes("androidmanifest.xml"));
  const javaFiles = filteredFiles.filter(
    (f) =>
      (f.path.endsWith(".kt") || f.path.endsWith(".java")) &&
      !f.path.toLowerCase().includes("androidmanifest.xml")
  );
  const layoutFiles = filteredFiles.filter((f) => f.path.toLowerCase().includes("res/layout/"));
  const resourceFiles = filteredFiles.filter(
    (f) =>
      f.path.toLowerCase().includes("res/") &&
      !f.path.toLowerCase().includes("res/layout/")
  );
  const gradleFiles = filteredFiles.filter(
    (f) =>
      f.path.toLowerCase().endsWith(".gradle") ||
      f.path.toLowerCase().endsWith(".gradle.kts") ||
      f.path.toLowerCase().endsWith(".properties")
  );

  const getFileIcon = (path: string) => {
    const low = path.toLowerCase();
    if (low.includes("androidmanifest.xml")) return <Smartphone className="w-4 h-4 text-emerald-400" />;
    if (low.endsWith(".kt")) return <FileCode className="w-4 h-4 text-purple-400" />;
    if (low.endsWith(".java")) return <FileCode className="w-4 h-4 text-orange-400" />;
    if (low.endsWith(".xml")) return <FileCode className="w-4 h-4 text-sky-400" />;
    if (low.endsWith(".gradle") || low.endsWith(".gradle.kts")) return <FileText className="w-4 h-4 text-teal-400" />;
    return <FileText className="w-4 h-4 text-slate-400" />;
  };

  const renderFileItem = (file: AndroidFile) => {
    const isSelected = file.path === selectedPath;
    const fileName = file.path.split("/").pop() || file.path;

    return (
      <div
        key={file.path}
        onClick={() => {
          onSelectFile(file.path);
          onCloseMobileFiles?.();
        }}
        className={`group flex items-center justify-between px-2.5 py-1.5 rounded-md cursor-pointer text-xs transition-colors ${
          isSelected
            ? "bg-sky-500/15 text-sky-300 font-semibold border-l-2 border-sky-400"
            : "text-slate-300 hover:bg-slate-800/60 hover:text-slate-100"
        }`}
      >
        <div className="flex items-center gap-2 truncate pr-2">
          {getFileIcon(file.path)}
          <span className="truncate">{fileName}</span>
          {file.isAutoGenerated && (
            <span
              className="bg-emerald-950 text-emerald-400 text-[9px] px-1 py-0.2 rounded border border-emerald-800/60 font-medium"
              title="Auto-generated by AI"
            >
              AI
            </span>
          )}
        </div>

        <button
          onClick={(e) => {
            e.stopPropagation();
            onDeleteFile(file.path);
          }}
          className="opacity-0 group-hover:opacity-100 text-slate-500 hover:text-red-400 p-0.5 rounded transition-opacity"
          title="Delete file"
        >
          <Trash2 className="w-3.5 h-3.5" />
        </button>
      </div>
    );
  };

  return (
    <aside
      className={`w-64 border-r flex flex-col h-full select-none transition-colors ${
        ideTheme === "light"
          ? "bg-slate-50 border-slate-200 text-slate-800"
          : "bg-slate-900 border-slate-800 text-slate-300"
      }`}
    >
      {/* Search & Add Header */}
      <div className="p-2.5 border-b border-slate-800 flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Project View</span>
          <div className="flex items-center gap-1">
            <button
              onClick={() => setIsCreating(!isCreating)}
              className="p-1 hover:bg-slate-800 text-slate-300 hover:text-white rounded transition-colors"
              title="Create new Android file"
            >
              <Plus className="w-4 h-4" />
            </button>
            {onCloseMobileFiles && (
              <button
                onClick={onCloseMobileFiles}
                className="p-1 md:hidden hover:bg-slate-800 text-slate-400 hover:text-rose-400 rounded transition-colors"
                title="Close files drawer"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        <div className="relative">
          <Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-slate-500" />
          <input
            type="text"
            placeholder="Search files..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-950 text-xs text-slate-200 pl-8 pr-2.5 py-1.5 rounded-md border border-slate-800 focus:outline-none focus:border-slate-700"
          />
        </div>

        {isCreating && (
          <form onSubmit={handleCreateFile} className="mt-1 flex flex-col gap-1.5 bg-slate-950 p-2 rounded border border-slate-800">
            <input
              type="text"
              placeholder="e.g. MyHelper.kt or activity_detail.xml"
              value={newFilePath}
              onChange={(e) => setNewFilePath(e.target.value)}
              className="bg-slate-900 text-xs text-slate-100 px-2 py-1 rounded border border-slate-700 focus:outline-none"
              autoFocus
            />
            <div className="flex justify-end gap-1">
              <button
                type="button"
                onClick={() => setIsCreating(false)}
                className="text-[11px] text-slate-400 px-2 py-0.5 hover:text-white"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold text-[11px] px-2.5 py-0.5 rounded"
              >
                Add File
              </button>
            </div>
          </form>
        )}
      </div>

      {/* File Sections List */}
      <div className="flex-1 overflow-y-auto p-2 space-y-3 custom-scrollbar">
        {/* Manifest Section */}
        <div>
          <div className="flex items-center gap-1.5 px-1 py-1 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <Smartphone className="w-3.5 h-3.5 text-emerald-400" />
            <span>Manifests</span>
          </div>
          <div className="pl-2 space-y-0.5">{manifests.map(renderFileItem)}</div>
        </div>

        {/* Java / Kotlin Source Section */}
        <div>
          <div className="flex items-center gap-1.5 px-1 py-1 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <FileCode className="w-3.5 h-3.5 text-purple-400" />
            <span>java / kotlin</span>
          </div>
          <div className="pl-2 space-y-0.5">{javaFiles.map(renderFileItem)}</div>
        </div>

        {/* Layout XML Section */}
        <div>
          <div className="flex items-center gap-1.5 px-1 py-1 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <Folder className="w-3.5 h-3.5 text-sky-400" />
            <span>res/layout</span>
          </div>
          <div className="pl-2 space-y-0.5">{layoutFiles.map(renderFileItem)}</div>
        </div>

        {/* Other Resources */}
        <div>
          <div className="flex items-center gap-1.5 px-1 py-1 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <Folder className="w-3.5 h-3.5 text-amber-400" />
            <span>res/values & icons</span>
          </div>
          <div className="pl-2 space-y-0.5">{resourceFiles.map(renderFileItem)}</div>
        </div>

        {/* Gradle Scripts */}
        <div>
          <div className="flex items-center gap-1.5 px-1 py-1 text-xs font-bold text-slate-400 uppercase tracking-wider">
            <FileText className="w-3.5 h-3.5 text-teal-400" />
            <span>Gradle Scripts</span>
          </div>
          <div className="pl-2 space-y-0.5">{gradleFiles.map(renderFileItem)}</div>
        </div>
      </div>
    </aside>
  );
};
