export interface AndroidFile {
  path: string; // e.g. "app/src/main/AndroidManifest.xml"
  content: string;
  isAutoGenerated?: boolean;
  hasErrors?: boolean;
}

export interface AndroidProject {
  id: string;
  name: string;
  packageName: string;
  versionName: string;
  versionCode: number;
  minSdk: number;
  targetSdk: number;
  compileSdk: number;
  files: AndroidFile[];
  updatedAt: string;
  lastSyncedAt?: string;
  githubRepo?: {
    owner: string;
    repo: string;
    branch: string;
    autoSync: boolean;
  };
}

export interface DiagnosticIssue {
  id: string;
  filePath: string;
  line?: number;
  severity: "error" | "warning" | "missing_file";
  message: string;
  suggestion: string;
  codeSnippet?: string;
}

export interface ValidationReport {
  isValid: boolean;
  missingFiles: string[];
  issues: DiagnosticIssue[];
}

export interface BuildLogStep {
  id: string;
  name: string;
  status: "pending" | "running" | "success" | "error";
  durationMs?: number;
  logs: string[];
}

export interface BuildOutput {
  success: boolean;
  apkUrl?: string;
  aabUrl?: string;
  sourceZipUrl?: string;
  apkSizeMb?: number;
  buildTimeMs?: number;
  logs: BuildLogStep[];
  error?: string;
}

export interface LayoutComponent {
  id: string;
  type:
    | "TextView"
    | "Button"
    | "EditText"
    | "ImageView"
    | "CardView"
    | "RecyclerView"
    | "FloatingActionButton"
    | "ProgressBar"
    | "Switch"
    | "LinearLayout"
    | "ConstraintLayout";
  label: string;
  attributes: Record<string, string>;
  children?: LayoutComponent[];
}

export interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
  branch: string;
  autoSync: boolean;
  lastCommitSha?: string;
  isSyncing?: boolean;
}

export interface ProjectSnapshot {
  id: string;
  timestamp: string;
  title: string;
  description: string;
  project: AndroidProject;
  type: "auto_save" | "manual_backup" | "ai_repair" | "template_load";
}

export interface BuildHistoryRecord {
  id: string;
  timestamp: string;
  projectName: string;
  versionName: string;
  success: boolean;
  apkSizeMb?: number;
  apkUrl?: string;
  logsCount: number;
}

export interface GitHubSyncHistoryRecord {
  id: string;
  timestamp: string;
  owner: string;
  repo: string;
  branch: string;
  status: "success" | "failed";
  message: string;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
}
